name: Label Changed Packages
description: Adds pull request labels for monorepo packages that have changed between git branches or tags
inputs:
  GITHUB_TOKEN:
    description: The GitHub Action token
    required: true
  diff-by:
    description: Determine what has changed by comparing against the next branch or the most recent git release tag. (branch or tag)
    required: false
    default: branch
  target-branch:
    description: Other branch to compare against. Only applies to diff-by=branch and non-pull requests events
    required: false
    default: ''
  skip-labels:
    description: Comma/newline delimited list of labels to ignore
    required: false
    default: ''
  dry-run:
    description: Do NOT push to the pull request. Only output the labels
    required: false
    default: "false"
  prefix:
    description: Label prefix
    required: false
    default: "deploy:"
outputs:
  labels:
    description: Comma separated list of app labels
runs:
  using: node12
  main: index.js
