name: Lambda Deploy
description: Deploy the S3 zip files to AWS Lambda
inputs:
  function:
    description: Function name
    required: true
  env:
    description: Override the target env [dev,qa,prod,hc]. Defaults to the branch name.
    required: false
  staging-bucket:
    description: S3 artifact bucket
    required: false
    default: rss-artifact
runs:
  using: node12
  main: index.js
  post: post/index.js
  post-if: success()
